# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gliding_box <- function(C, box_sizes) {
    .Call(`_lacunaRity_gliding_box`, C, box_sizes)
}

.gliding_box_periodic <- function(C, box_sizes) {
    .Call(`_lacunaRity_gliding_box_periodic`, C, box_sizes)
}

.voxelize_C <- function(pc, edge_length, threads = 1L) {
    .Call(`_lacunaRity_voxelization_rcpp`, pc, edge_length, threads)
}

